# Generated by Django 5.1.5 on 2025-02-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('area', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('type', models.SmallIntegerField(choices=[(1, '剩餘車位數'), (2, '靜態停車場資料')])),
                ('summary', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('pay_ex', models.TextField(blank=True, null=True, verbose_name='pay info')),
                ('service_time', models.CharField(blank=True, max_length=255, null=True)),
                ('tw97x', models.FloatField(blank=True, null=True, verbose_name='x-coordinate')),
                ('tw97y', models.FloatField(blank=True, null=True, verbose_name='y-coordinate')),
                ('total_car', models.SmallIntegerField(blank=True, null=True)),
                ('total_motor', models.SmallIntegerField(blank=True, null=True)),
                ('total_bike', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
